In [1]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [5]:
df = pd.read_csv('../data/synthetic-imports-declarations.csv', encoding = "ISO-8859-1")

In [8]:
df['importer.id'].nunique()

8653

In [11]:
np.mean(df['illicit'])

0.07579

In [14]:
df['tariff.code'].nunique()

1894

In [2]:
df = pd.read_csv('./data/tdata.csv',encoding = "ISO-8859-1")
# df = df[df['Source']=='T']
# df = df.sort_values(by='sgd.date',ascending=True)
# df.reset_index()
# df.loc[:, 'HS6'] = df['tariff.code'].apply(lambda x: int(x // 10000))
# df.loc[:, 'HS4'] = df['HS6'].apply(lambda x: int(x // 100))
# df.loc[:, 'HS2'] = df['HS4'].apply(lambda x: int(x // 100))
df[:5]

,sgd.date,office.id,importer.id,tariff.code,country,last.departure.code,contract.party.code,cif.value,total.taxes,gross.weight,quantity,revenue,illicit
0,15-01-01,16,IMP103557,8039010002,Pays94,Pays94,Pays295,20453.37,19084.15,39835.0,39835.0,0.0,0
1,15-01-01,11,IMP23760,84799080002,Pays190,Pays190,Pays190,10635.20,10.00,48.0,48.0,0.0,0
2,15-01-01,11,IMP23760,84799080002,Pays413,Pays78,Pays413,629.91,10.00,2.0,2.0,0.0,0
3,15-01-01,11,IMP23760,84669280003,Pays138,Pays394,Pays394,129.13,10.00,1.0,1.0,0.0,0
4,15-01-01,11,IMP23760,84669280003,Pays138,Pays394,Pays394,8472.21,10.00,3.0,3.0,0.0,0

In [3]:
from datetime import datetime as dt
df.loc[:, 'HS6'] = df['tariff.code'].apply(lambda x: int(x // 10000))
df.loc[:, 'HS4'] = df['HS6'].apply(lambda x: int(x // 100))
df.loc[:, 'HS2'] = df['HS4'].apply(lambda x: int(x // 100))
df = df.sort_values(by='sgd.date',ascending=True)
df['sgd.date'] = df['sgd.date'].apply(lambda x: dt.strptime(x, '%y-%m-%d'))
df.loc[:,'YEAR'] = df['sgd.date'].dt.year
df.dropna(subset=['country'])
df.reset_index()

,index,sgd.date,office.id,importer.id,tariff.code,country,last.departure.code,contract.party.code,cif.value,total.taxes,gross.weight,quantity,revenue,illicit,HS6,HS4,HS2,YEAR
0,0,2015-01-01,16,IMP103557,8039010002,Pays94,Pays94,Pays295,20453.37,19084.15,39835.0,39835.0,0.0,0,803901,8039,80,2015
1,14,2015-01-01,11,IMP23760,32041900008,Pays138,Pays138,Pays138,88.85,10.00,3.0,3.0,0.0,0,3204190,32041,320,2015
2,13,2015-01-01,22,IMP116740,62034231032,Pays394,Pays190,Pays190,2713.76,10.00,60.0,61.0,0.0,0,6203423,62034,620,2015
3,12,2015-01-01,16,IMP40824,21069098982,Pays362,Pays362,Pays362,14811.24,9946.63,2949.0,2949.0,0.0,0,2106909,21069,210,2015
4,11,2015-01-01,16,IMP40824,17049071096,Pays362,Pays362,Pays362,1467.88,914.41,504.0,504.0,0.0,0,1704907,17049,170,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4171645,4171490,2019-12-31,62,IMP29823,70071110107,Pays78,Pays125,Pays125,621.15,357.57,6.0,3.0,0.0,0,7007111,70071,700,2019
4171646,4171491,2019-12-31,62,IMP29823,87082190003,Pays78,Pays125,Pays125,339.63,199.81,4.0,4.0,0.0,0,8708219,87082,870,2019
4171647,4171492,2019-12-31,62,IMP29823,85439000092,Pays78,Pays125,Pays125,236.42,97.12,2.0,2.0,0.0,0,8543900,85439,854,2019
4171648,4171494,2019-12-31,53,IMP99627,87032290309,Pays125,Pays125,Pays125,17929.17,5095.74,1000.0,1.0,0.0,0,8703229,87032,870,2019
4171649,4171649,2019-12-31,31,IMP120721,85151990006,Pays190,Pays190,Pays190,1882.89,10.00,18.0,6.0,0.0,0,8515199,85151,851,2019

In [4]:
group = df.groupby(['YEAR','HS2','country'])['HS2'].size().unstack(level=2)
group

country   Pays10  Pays102  Pays104  Pays107  Pays109  Pays111  Pays113  \
YEAR HS2
2015 10      NaN      NaN      NaN      NaN      NaN      NaN      NaN
     20      NaN      NaN      NaN      NaN      NaN      NaN      NaN
     21      NaN      NaN      NaN      NaN      NaN      NaN      NaN
     30      NaN      NaN      2.0      NaN      2.0      NaN      1.0
     40      NaN      1.0      6.0      NaN      NaN      NaN      NaN
...          ...      ...      ...      ...      ...      ...      ...
2019 960     NaN      2.0     22.0      NaN      NaN      NaN      NaN
     961     NaN     10.0      NaN      NaN      NaN      NaN      NaN
     962     NaN      NaN      NaN      NaN      NaN      NaN      NaN
     970     NaN      NaN      NaN      NaN      NaN      NaN      NaN
     980     NaN     22.0      1.0      NaN      NaN      NaN      NaN

country   Pays116  Pays117  Pays119  ...  Pays78  Pays79  Pays8  Pays85  \
YEAR HS2                             ...
2015 10       NaN      NaN      NaN  ...     NaN     NaN    NaN     NaN
     20       NaN      NaN      NaN  ...     NaN     NaN    NaN     NaN
     21       NaN      NaN      NaN  ...     NaN     NaN    NaN     NaN
     30       NaN      NaN      NaN  ...    44.0     1.0    NaN     NaN
     40       NaN      NaN      NaN  ...     1.0     NaN    NaN     NaN
...           ...      ...      ...  ...     ...     ...    ...     ...
2019 960      NaN      NaN      NaN  ...  1532.0    33.0    NaN     NaN
     961      NaN      NaN      NaN  ...  1249.0     8.0    NaN     NaN
     962      NaN      NaN      NaN  ...    43.0     NaN    NaN     NaN
     970      NaN      NaN      NaN  ...     NaN     NaN    NaN     NaN
     980      NaN      NaN      NaN  ...    30.0     NaN    NaN     NaN

country   Pays87  Pays89  Pays90  Pays94  Pays96  Pays98
YEAR HS2
2015 10      NaN     NaN     NaN     NaN     NaN     NaN
     20      NaN     NaN     NaN     NaN     NaN     NaN
     21      NaN     NaN     NaN     NaN     NaN     NaN
     30      NaN     NaN     NaN     NaN     NaN     NaN
     40      NaN     NaN     NaN     NaN     NaN     NaN
...          ...     ...     ...     ...     ...     ...
2019 960     NaN     NaN     NaN     NaN     NaN     NaN
     961     NaN     NaN     NaN     NaN     NaN     NaN
     962     NaN     NaN     NaN     NaN     NaN     NaN
     970     NaN     NaN     NaN     NaN     NaN     NaN
     980     NaN     NaN     NaN     NaN     NaN     NaN

[873 rows x 195 columns]

In [4]:
def count_per_year(df):
    count = df['YEAR'].value_counts()
#     print(count)
    num_year = len(count)
    start_year = df['YEAR'].min()
    years = count.index.values.tolist()
    years.sort()
    return count, years

# def items_shift(df):
#     startRow = 0
#     items = []
#     count, years = count_per_year(df)
# #     print(count)
#     for year in years:
#         y = df[df['YEAR']==year]
# #         print(y['HS2'].value_counts().sort_index())
#         hist, bin_edges = np.histogram(y['HS2'],bins=99,density=True)
# #         _ = plt.hist(y['HS2'],bins=99,density=True)
# #         plt.show()
#         print(y['HS2'])
# #         print(year)
#         items.append(hist)
#     return items
# def countries_shift(df):
#     count, years = count_per_year(df)
#     num_countries = len(df['country'].value_counts(dropna=True))
# #     print(num_countries)
#     countries = [0 for i in range(len(years))]
# #     print(type(countries))
# #     print(years)
#     for year in range(len(years)):
#         y = df[df['YEAR']==years[year]]
#         y.dropna(axis=0, how = 'any')
#         try:
#             ct = np.array(y['country'], dtype=int)
#             hist, bin_edges = np.histogram(ct,bins=int(num_countries),density=True)
#             _ = plt.hist(ct,bins=int(num_countries),density=True)
# #             plt.show()
# #             print(years[year])
#             countries[year] = hist
#         except:
#             pass
#     return years, countries

def items_shift(df):
    startRow = 0
    count, years = count_per_year(df)
#     print(count)
    all_years_prob = []
    for year in years:
        y = df[df['YEAR']==year]
        y = y['HS2'].value_counts()
        s = y.sum()
        prob = y.apply(lambda x: x/s)
        all_years_prob.append(prob)
        print(all_years_prob)
    return all_years_prob

def countries_shift(df):
    startRow = 0
    count, years = count_per_year(df)
#     print(count)
    all_years_prob = []
    for year in years:
        y = df[df['YEAR']==year]
        y = y['country'].value_counts()
        s = y.sum()
        prob = y.apply(lambda x: x/s)
        all_years_prob.append(prob)
        print(all_years_prob)
    return all_years_prob

def add_offset(arr,num_year):
    for i in range(num_year):
        try:
            offset = np.full(arr[i].size,0.000000001)
            arr[i] += offset
        except:
            pass
    return arr

count, num_year = count_per_year(df)
items = items_shift(df)
countries = countries_shift(df)
# # print(countries)
items = add_offset(items,len(num_year))
countries = add_offset(countries,len(num_year))
# print(countries)

[870    0.102309
848    0.051658
392    0.042627
853    0.040133
841    0.035206
         ...
510    0.000022
260    0.000013
531    0.000007
262    0.000006
41     0.000005
Name: HS2, Length: 174, dtype: float64]
[870    0.102309
848    0.051658
392    0.042627
853    0.040133
841    0.035206
         ...
510    0.000022
260    0.000013
531    0.000007
262    0.000006
41     0.000005
Name: HS2, Length: 174, dtype: float64, 870    0.094404
848    0.049140
392    0.038451
853    0.038075
851    0.035604
         ...
360    0.000019
260    0.000010
531    0.000007
41     0.000005
262    0.000002
Name: HS2, Length: 174, dtype: float64]
[870    0.102309
848    0.051658
392    0.042627
853    0.040133
841    0.035206
         ...
510    0.000022
260    0.000013
531    0.000007
262    0.000006
41     0.000005
Name: HS2, Length: 174, dtype: float64, 870    0.094404
848    0.049140
392    0.038451
853    0.038075
851    0.035604
         ...
360    0.000019
260    0.000010
531    0.000007
41     0.000005
262    0.000002
Name: HS2, Length: 174, dtype: float64, 870    0.090674
848    0.050763
392    0.041104
853    0.040948
851    0.036333
         ...
510    0.000016
962    0.000016
260    0.000012
41     0.000008
262    0.000003
Name: HS2, Length: 175, dtype: float64]
[870    0.102309
848    0.051658
392    0.042627
853    0.040133
841    0.035206
         ...
510    0.000022
260    0.000013
531    0.000007
262    0.000006
41     0.000005
Name: HS2, Length: 174, dtype: float64, 870    0.094404
848    0.049140
392    0.038451
853    0.038075
851    0.035604
         ...
360    0.000019
260    0.000010
531    0.000007
41     0.000005
262    0.000002
Name: HS2, Length: 174, dtype: float64, 870    0.090674
848    0.050763
392    0.041104
853    0.040948
851    0.036333
         ...
510    0.000016
962    0.000016
260    0.000012
41     0.000008
262    0.000003
Name: HS2, Length: 175, dtype: float64, 870    0.087011
848    0.049869
392    0.044575
853    0.041082
851    0.035109
         ...
970    0.000015
531    0.000013
260    0.000010
262    0.000006
41     0.000004
Name: HS2, Length: 175, dtype: float64]
[870    0.102309
848    0.051658
392    0.042627
853    0.040133
841    0.035206
         ...
510    0.000022
260    0.000013
531    0.000007
262    0.000006
41     0.000005
Name: HS2, Length: 174, dtype: float64, 870    0.094404
848    0.049140
392    0.038451
853    0.038075
851    0.035604
         ...
360    0.000019
260    0.000010
531    0.000007
41     0.000005
262    0.000002
Name: HS2, Length: 174, dtype: float64, 870    0.090674
848    0.050763
392    0.041104
853    0.040948
851    0.036333
         ...
510    0.000016
962    0.000016
260    0.000012
41     0.000008
262    0.000003
Name: HS2, Length: 175, dtype: float64, 870    0.087011
848    0.049869
392    0.044575
853    0.041082
851    0.035109
         ...
970    0.000015
531    0.000013
260    0.000010
262    0.000006
41     0.000004
Name: HS2, Length: 175, dtype: float64, 870    0.075861
848    0.050207
392    0.045489
853    0.042316
851    0.034182
         ...
970    0.000023
531    0.000013
260    0.000010
41     0.000006
262    0.000003
Name: HS2, Length: 175, dtype: float64]
[Pays125    0.173188
Pays78     0.154733
Pays190    0.142728
Pays138    0.106102
Pays396    0.055482
             ...
Pays447    0.000001
Pays400    0.000001
Pays417    0.000001
Pays117    0.000001
Pays119    0.000001
Name: country, Length: 170, dtype: float64]
[Pays125    0.173188
Pays78     0.154733
Pays190    0.142728
Pays138    0.106102
Pays396    0.055482
             ...
Pays447    0.000001
Pays400    0.000001
Pays417    0.000001
Pays117    0.000001
Pays119    0.000001
Name: country, Length: 170, dtype: float64, Pays78     0.166653
Pays125    0.158256
Pays190    0.135898
Pays138    0.100782
Pays396    0.060325
             ...
Pays45     0.000001
Pays127    0.000001
Pays164    0.000001
Pays154    0.000001
Pays166    0.000001
Name: country, Length: 169, dtype: float64]
[Pays125    0.173188
Pays78     0.154733
Pays190    0.142728
Pays138    0.106102
Pays396    0.055482
             ...
Pays447    0.000001
Pays400    0.000001
Pays417    0.000001
Pays117    0.000001
Pays119    0.000001
Name: country, Length: 170, dtype: float64, Pays78     0.166653
Pays125    0.158256
Pays190    0.135898
Pays138    0.100782
Pays396    0.060325
             ...
Pays45     0.000001
Pays127    0.000001
Pays164    0.000001
Pays154    0.000001
Pays166    0.000001
Name: country, Length: 169, dtype: float64, Pays78     0.171324
Pays125    0.148174
Pays190    0.134881
Pays138    0.103301
Pays396    0.064075
             ...
Pays184    0.000001
Pays335    0.000001
Pays299    0.000001
Pays441    0.000001
Pays10     0.000001
Name: country, Length: 168, dtype: float64]
[Pays125    0.173188
Pays78     0.154733
Pays190    0.142728
Pays138    0.106102
Pays396    0.055482
             ...
Pays447    0.000001
Pays400    0.000001
Pays417    0.000001
Pays117    0.000001
Pays119    0.000001
Name: country, Length: 170, dtype: float64, Pays78     0.166653
Pays125    0.158256
Pays190    0.135898
Pays138    0.100782
Pays396    0.060325
             ...
Pays45     0.000001
Pays127    0.000001
Pays164    0.000001
Pays154    0.000001
Pays166    0.000001
Name: country, Length: 169, dtype: float64, Pays78     0.171324
Pays125    0.148174
Pays190    0.134881
Pays138    0.103301
Pays396    0.064075
             ...
Pays184    0.000001
Pays335    0.000001
Pays299    0.000001
Pays441    0.000001
Pays10     0.000001
Name: country, Length: 168, dtype: float64, Pays78     0.178525
Pays125    0.134844
Pays190    0.131068
Pays138    0.102485
Pays396    0.062061
             ...
Pays254    0.000001
Pays48     0.000001
Pays233    0.000001
Pays14     0.000001
Pays90     0.000001
Name: country, Length: 170, dtype: float64]
[Pays125    0.173188
Pays78     0.154733
Pays190    0.142728
Pays138    0.106102
Pays396    0.055482
             ...
Pays447    0.000001
Pays400    0.000001
Pays417    0.000001
Pays117    0.000001
Pays119    0.000001
Name: country, Length: 170, dtype: float64, Pays78     0.166653
Pays125    0.158256
Pays190    0.135898
Pays138    0.100782
Pays396    0.060325
             ...
Pays45     0.000001
Pays127    0.000001
Pays164    0.000001
Pays154    0.000001
Pays166    0.000001
Name: country, Length: 169, dtype: float64, Pays78     0.171324
Pays125    0.148174
Pays190    0.134881
Pays138    0.103301
Pays396    0.064075
             ...
Pays184    0.000001
Pays335    0.000001
Pays299    0.000001
Pays441    0.000001
Pays10     0.000001
Name: country, Length: 168, dtype: float64, Pays78     0.178525
Pays125    0.134844
Pays190    0.131068
Pays138    0.102485
Pays396    0.062061
             ...
Pays254    0.000001
Pays48     0.000001
Pays233    0.000001
Pays14     0.000001
Pays90     0.000001
Name: country, Length: 170, dtype: float64, Pays78     0.182877
Pays125    0.134182
Pays190    0.127962
Pays138    0.100758
Pays396    0.064763
             ...
Pays68     0.000001
Pays441    0.000001
Pays194    0.000001
Pays166    0.000001
Pays233    0.000001
Name: country, Length: 165, dtype: float64]

In [5]:
def kl_divergence(p, q):
    try:
        return (stats.entropy(p,q))
    except:
        pass
    
# def shifting_check(factor,years):
#     for i in range(len(factor)-1):
#         for j in range(len(factor[i])):
#             if abs(factor[i+1][j] - factor[i][j]) >0.001:
#                 print("{} ~ {} -- {} -- {} : {}".format(years[i],years[i+1],j,factor[i+1][j],factor[i][j]))
#         print("{} ~ {} : {}".format(years[i],years[i+1],kl_divergence(factor[i],factor[i+1])))
def shifting_check(factor,years):
    for i in range(len(factor)-1):
        for j in factor[i].index.tolist():
#             print(j)
            try:
                if abs(factor[i+1][j] - factor[i][j]) >0.005:
                    print("{} ~ {} -- {} -- {} : {}".format(years[i],years[i+1],j,factor[i+1][j],factor[i][j]))
            except:
                pass
           
#         print("{} ~ {} : {}".format(years[i],years[i+1],kl_divergence(factor[i],factor[i+1])))        
print("====ITEMS DOMAIN CHECK")
shifting_check(items,num_year)
print("====Country")
shifting_check(countries,num_year)

====ITEMS DOMAIN CHECK
2015 ~ 2016 -- 870 -- 0.09440422707218814 : 0.1023091761301896
2015 ~ 2016 -- 330 -- 0.030005898402635626 : 0.016185517586586873
2016 ~ 2017 -- 330 -- 0.014446853641636953 : 0.030005898402635626
2018 ~ 2019 -- 870 -- 0.07586084385084413 : 0.08701107487192362
====Country
2015 ~ 2016 -- Pays125 -- 0.1582564191945227 : 0.17318756034056448
2015 ~ 2016 -- Pays78 -- 0.1666534048696118 : 0.154732572856029
2015 ~ 2016 -- Pays190 -- 0.13589752354584658 : 0.1427280845515148
2015 ~ 2016 -- Pays138 -- 0.10078236068051558 : 0.10610236886834307
2015 ~ 2016 -- Pays450 -- 0.03461590131318369 : 0.02830509062223437
2016 ~ 2017 -- Pays125 -- 0.14817404374161597 : 0.1582564191945227
2016 ~ 2017 -- Pays450 -- 0.04730243172548883 : 0.03461590131318369
2017 ~ 2018 -- Pays78 -- 0.17852523210003374 : 0.17132419872075788
2017 ~ 2018 -- Pays125 -- 0.13484374607039176 : 0.14817404374161597
2017 ~ 2018 -- Pays450 -- 0.05620663561561797 : 0.04730243172548883
2018 ~ 2019 -- Pays382 -- 0.009179480156295779 : 0.014993290665599646

In [20]:
temp = df[df['country']=='Pays450']
year = [2015,2016,2017,2018,2019]
for i in year:
    cur = temp[temp['YEAR']==i]
    count = cur['illicit'].value_counts()
    s = count.sum()
    ratio = count.apply(lambda x: x/s)
    print("YEAR {}".format(i))
    print(ratio)

# item32['HS2'].value_counts()

YEAR 2015
0    0.976377
1    0.023623
Name: illicit, dtype: float64
YEAR 2016
0    0.980507
1    0.019493
Name: illicit, dtype: float64
YEAR 2017
0    0.966498
1    0.033502
Name: illicit, dtype: float64
YEAR 2018
0    0.946632
1    0.053368
Name: illicit, dtype: float64
YEAR 2019
0    0.926479
1    0.073521
Name: illicit, dtype: float64

In [34]:
item = df[df['HS2']==830]
# item32['YEAR'].value_counts()
item['country'].value_counts()
for i in year:
    c = item[item['YEAR']==i]
    count_country = c['country'].value_counts()
    sum_countries = count_country.sum()
    countries_ration = count_country.apply(lambda x: x/sum_countries)
    print(countries_ration)
    print("===")
#     s = count.sum()
#     ratio = count.apply(lambda x: x/s)
#     print("YEAR {}".format(i))
#     print(ratio)

Pays78     0.203176
Pays190    0.188524
Pays125    0.132660
Pays138    0.107254
Pays396    0.079899
             ...
Pays293    0.000072
Pays380    0.000072
Pays220    0.000072
Pays304    0.000072
Pays184    0.000072
Name: country, Length: 61, dtype: float64
===
Pays78     0.230371
Pays190    0.181203
Pays125    0.118017
Pays138    0.097990
Pays396    0.076583
             ...
Pays380    0.000069
Pays246    0.000069
Pays134    0.000069
Pays304    0.000069
Pays18     0.000069
Name: country, Length: 61, dtype: float64
===
Pays78     0.240979
Pays190    0.171840
Pays125    0.115880
Pays138    0.105149
Pays396    0.082607
Pays362    0.044797
Pays382    0.025279
Pays102    0.021966
Pays196    0.017645
Pays178    0.015916
Pays420    0.013972
Pays205    0.013396
Pays413    0.012964
Pays28     0.012748
Pays310    0.012315
Pays450    0.011883
Pays308    0.010443
Pays79     0.007562
Pays20     0.007058
Pays264    0.005185
Pays150    0.004105
Pays394    0.003961
Pays376    0.003961
Pays172    0.003889
Pays409    0.003817
Pays352    0.003817
Pays174    0.003385
Pays392    0.003025
Pays321    0.002665
Pays378    0.002593
Pays242    0.002377
Pays38     0.002017
Pays252    0.001512
Pays62     0.001224
Pays341    0.001152
Pays186    0.001080
Pays104    0.000864
Pays50     0.000792
Pays180    0.000576
Pays16     0.000432
Pays355    0.000360
Pays351    0.000360
Pays246    0.000360
Pays229    0.000288
Pays200    0.000288
Pays123    0.000288
Pays293    0.000216
Pays4      0.000144
Pays134    0.000144
Pays6      0.000072
Pays304    0.000072
Pays204    0.000072
Pays98     0.000072
Pays221    0.000072
Pays344    0.000072
Pays235    0.000072
Pays35     0.000072
Pays116    0.000072
Pays289    0.000072
Name: country, dtype: float64
===
Pays78     0.247404
Pays190    0.168294
Pays138    0.098791
Pays125    0.090965
Pays396    0.089881
Pays362    0.042848
Pays382    0.028126
Pays450    0.027662
Pays178    0.025182
Pays196    0.021153
Pays102    0.019371
Pays205    0.014412
Pays420    0.014024
Pays413    0.013637
Pays308    0.011545
Pays310    0.010150
Pays28     0.009375
Pays79     0.007438
Pays352    0.006586
Pays20     0.006121
Pays264    0.005424
Pays172    0.005036
Pays174    0.004184
Pays376    0.003409
Pays150    0.003254
Pays321    0.003022
Pays378    0.002867
Pays409    0.002402
Pays394    0.002170
Pays341    0.002170
Pays38     0.001860
Pays242    0.001782
Pays180    0.001395
Pays62     0.001240
Pays392    0.000852
Pays252    0.000775
Pays50     0.000697
Pays104    0.000620
Pays355    0.000542
Pays186    0.000542
Pays229    0.000465
Pays304    0.000310
Pays123    0.000310
Pays217    0.000232
Pays337    0.000155
Pays35     0.000155
Pays134    0.000155
Pays344    0.000077
Pays235    0.000077
Pays322    0.000077
Pays351    0.000077
Pays200    0.000077
Pays58     0.000077
Pays293    0.000077
Pays154    0.000077
Pays343    0.000077
Pays202    0.000077
Pays207    0.000077
Pays16     0.000077
Pays289    0.000077
Name: country, dtype: float64
===
Pays78     0.264351
Pays190    0.166057
Pays138    0.093117
Pays125    0.091063
Pays396    0.090528
Pays362    0.054906
Pays102    0.020980
Pays178    0.020802
Pays450    0.019909
Pays382    0.019016
Pays196    0.018659
Pays420    0.015356
Pays310    0.013570
Pays205    0.012945
Pays413    0.012856
Pays308    0.009553
Pays352    0.008481
Pays28     0.008481
Pays79     0.008124
Pays172    0.005535
Pays20     0.004285
Pays376    0.003839
Pays409    0.003750
Pays321    0.003571
Pays264    0.003482
Pays150    0.002768
Pays378    0.002768
Pays242    0.002589
Pays174    0.002143
Pays252    0.002053
Pays394    0.001875
Pays38     0.001607
Pays50     0.001518
Pays392    0.001250
Pays62     0.001161
Pays341    0.001161
Pays104    0.000982
Pays123    0.000803
Pays186    0.000714
Pays229    0.000625
Pays180    0.000625
Pays355    0.000357
Pays96     0.000268
Pays304    0.000268
Pays200    0.000179
Pays351    0.000179
Pays322    0.000179
Pays4      0.000089
Pays344    0.000089
Pays235    0.000089
Pays262    0.000089
Pays35     0.000089
Pays293    0.000089
Pays16     0.000089
Pays289    0.000089
Name: country, dtype: float64
===